#!/usr/bin/env bash

# MigBash is the script that implements simple migrations for your database


db_user='user'
db_pass='pass'
db_host='127.0.0.1'
db_name='db_name'
migration_table='tbl_migrations'

patches_path='./sql/'
date=`date '+%Y-%m-%d %H:%M:%S'`

# check if table exists
table_exists() {
    db_query=$(mysql --user="${db_user}" --password="${db_pass}" --host="${db_host}" -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '${1}' AND table_name = '${2}';")
    echo ${db_query} | awk '{print $2}'
}

# create table for migrations
create_table() {
    db_query=$(mysql --user="${db_user}" --password="${db_pass}" --host="${db_host}" ${db_name} -e "
    CREATE TABLE ${migration_table} (
            id INT(10) NOT NULL AUTO_INCREMENT,
            name CHAR(60) NULL DEFAULT NULL,
            date CHAR(60) NULL DEFAULT NULL,
            PRIMARY KEY (id)
    ) COLLATE='utf8_unicode_ci' ENGINE=InnoDB;
    ")
}

# check whether the patch was applied or not
is_applied() {
    patch=$(mysql --user="${db_user}" --password="${db_pass}" --host="${db_host}" ${db_name} -e "SELECT COUNT(*) FROM ${migration_table} WHERE name = '${1}';")
    echo ${patch} | awk '{print $2}'
}

# apply patch
apply_patch() {
    db_query=$(mysql --user="${db_user}" --password="${db_pass}" --host="${db_host}" ${db_name} < "${1}")
}

# log patch into migration's table
log_patch() {
    $(mysql --user="${db_user}" --password="${db_pass}" --host="${db_host}" ${db_name} -e "INSERT INTO ${migration_table} (name, date) VALUES ('${1}', '${date}');")
}

# check if provided folder exists
folder_exists() {
    if [ ! -d ${1} ]
    then
        echo 1
    fi
}

# apply migrations
migrate() {
    folder_exists=$(folder_exists ${patches_path})
    if [[ ${folder_exists} -ne 0 ]]
    then
        echo "Folder does not exists: '${patches_path}'"
    else
        for PATCH in $(ls ${patches_path})
        do
            patch_applied=$(is_applied "${PATCH}")
            if [[ ${patch_applied} -ne 0 ]]
            then
                echo -en "${PATCH} - skipped \r\n"
            else
                $(apply_patch ${patches_path}${PATCH})
                if [[ $? -ne 0 ]]
                then
                    echo -en '\E[47;31m'"\033[1m ${PATCH} - Failed...\033[0m \r\n"
                else
                    $(log_patch "${PATCH}")
                    echo -en "\033[1;32m ${PATCH} - Ok!\033[0m\r\n"
                fi
            fi
        done
    fi
}

tbl_exists=$(table_exists ${db_name} ${migration_table})

if [[ ${tbl_exists} -ne 0 ]]
then
    migrate
else
    $(create_table ${migration_table})
    migrate
fi
