#!/usr/bin/env bash

log_db='patches.db'
sqlite=`which sqlite3`
date=`date '+%Y-%m-%d %H:%M:%S'`

# patch_code=`cat "${PATCH}"`

# START TRANSACTION;
# INSERT INTO Test VALUES (5), (6);
# ROLLBACK;

create_log_db() {
    ${sqlite} $1  "CREATE TABLE log (id INTEGER PRIMARY KEY, name TEXT, date TEXT, success INTEGER);"
}

check() {
    ${sqlite} ${log_db} "SELECT COUNT(*) FROM log WHERE name='$1' AND success=1;"
}

patch_success() {
    ${sqlite} ${log_db} "INSERT INTO log (name, date, success) VALUES ('$1','$2', '$3');"
}

if [ ! -f ${log_db} ]; then
    create_log_db ${log_db}
fi

get_all() {
    for PATCH in ./*.sql
    do
        result=`check "${PATCH}"`
        if [[ ${result} -ne 0 ]]
        then
            echo "${PATCH} - skipped"
        else
            `patch_success "${PATCH}" "${date}" 1`
            # mig=`${db_do} < ${PATCH}`
            # if [[ $? -ne 0 ]]
            # then
            #     echo -en '\E[47;31m'"\033[1m ${PATCH} - Failed...\033[0m \r\n"
            # else
            #     echo -en "\033[1;32m ${PATCH} - Ok!\033[0m\r\n"
            #     echo "${PATCH}" >> ${mig_used}
            # fi
        fi
    done
}

get_all

# find_new_patches() {
# }

# apply_new_patches() {
# }
